version: '3.7'
services:
  node-app:
    build: ./gate-simulator
    image: node-app:1.0
    container_name: node
    ports:
      - '9999:9999'
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123456